security:
  oauth2:
    resourceserver:
      issuer: http://localhost:8888/auth/realms/master
      jwk:
        jwk-set-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/certs
  oauth2bis:
    resourceserver:
      issuer: http://localhost:8888/auth/realms/masterbis
      jwk:
        jwk-set-uri: http://localhost:8888/auth/realms/masterbis/protocol/openid-connect/certs        